# 侧边导航
aside_menu:
  home:
    link: /index.html
    icon: wendang
  archives:
    link: /archives/index.html
    icon: wendang1
  tags:
    link: /tags/index.html
    icon: biaoqian1
  links:
    link: /links/index.html
    icon: lianjie
  about:
    link: /about/index.html
    icon: guanyu
  rss:
    link: /atom.xml
    icon: rss

# 侧边展示，信息标签只能自己修改了，位置 layout/_partial/_aside.ejs
aside_show:
  avatar: /img/avatar.png
  name: 恋恋风辰
  caption: 个人博客
  description: 重剑无锋，大巧不工。

# 页脚请自己在主题的 layout/_partial/_footer.ejs 里修改
# 文章的代码块样式请在 source/css/_partial/_post/_highlight.scss 中修改

# 友情链接
links:
  '我的博客园':
    avatar: /img/links/cnblogs.jpg
    link: http://www.cnblogs.com/secondtonone1/
    description: 博客园主页
  '张宇':
    avatar: /img/links/zy.png
    link: http://main.yinyst.com/
    description: 游戏开发者，cocos2d前端开发。
  


# 畅言
comments: false
changyan_appid: cyt8PcC7O
changyan_appkey: 776c9cb6341329511a82398f0c365bd8

# 搜索
search: true
